# Generated by Django 5.0.6 on 2024-06-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUI', models.BigIntegerField(max_length=8)),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cursor', models.IntegerField()),
                ('nombre_curso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotasAlumnosPorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui_alumno', models.BigIntegerField(max_length=8)),
                ('id_curso', models.IntegerField()),
                ('nota', models.IntegerField()),
            ],
        ),
    ]
