# Generated by Django 5.0.6 on 2024-06-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='CUI',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='notasalumnosporcurso',
            name='cui_alumno',
            field=models.IntegerField(max_length=8),
        ),
    ]
