# Generated by Django 5.0.6 on 2024-06-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_alumnos_cui_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='CUI',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notasalumnosporcurso',
            name='cui_alumno',
            field=models.IntegerField(),
        ),
    ]
