# Generated by Django 5.0.6 on 2024-06-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_alumnos_cui_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnos',
            new_name='Alumno',
        ),
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
    ]
