# Generated by Django 5.0.6 on 2024-06-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_genre_alter_author_options_author_date_of_death_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the language of the book (e.g. English, Spanish, French, etc.)', max_length=100, unique=True)),
            ],
        ),
    ]
